import React, { createContext, useContext, useState } from 'react'

const LangContext = createContext(null)

export const LANGS = ['uk', 'en', 'ru']
export const LANG_LABELS = { uk: 'Укр', en: 'Eng', ru: 'Рус' }

export const T = {
  uk: {
    appTitle: 'OKX P2P Tracker',
    loading: 'Завантаження...',
    error: 'Помилка завантаження',
    logout: 'Вийти',
    // Tabs
    tabDashboard: 'Дашборд',
    tabCards: 'Карти',
    tabUpload: 'Завантажити скрін',
    // Dashboard
    period: 'Період',
    dateFrom: 'Від',
    dateTo: 'До',
    applyFilter: 'Застосувати',
    resetFilter: 'Скинути',
    filterThisMonth: 'Цей місяць',
    filterPrevMonth: 'Минулий місяць',
    filterThisYear: 'Цей рік',
    statSold: 'Продано USDT → UAH',
    statBought: 'Витрачено UAH на покупку',
    statProfit: 'Прибуток P2P',
    statProfitSub: 'продажі − покупки',
    statDeposit: 'Поповнення USDT',
    recentTx: 'Останні транзакції',
    noData: 'Немає даних. Завантажте CSV.',
    colType: 'Тип',
    colDate: 'Дата',
    colUsdt: 'USDT',
    colUah: 'UAH',
    colPrice: 'Ціна',
    colCounterparty: 'Контрагент',
    prevPage: '← Назад',
    nextPage: 'Далі →',
    pageOf: (p, t) => `Стор. ${p} з ${t}`,
    // TX types
    buy_usdt: '🟢 Купівля USDT',
    sell_usdt: '🔴 Продаж USDT',
    deposit: '💰 Поповнення',
    withdrawal: '📤 Виведення',
    cancel_order: '↩️ Скасування',
    internal: '🔄 Внутрішній',
    other: '❓ Інше',
    // Auth
    authLogin: 'Вхід в акаунт',
    authRegister: 'Реєстрація нового акаунту',
    authEmail: 'Email',
    authPassword: 'Пароль',
    authSubmitLogin: 'Увійти',
    authSubmitRegister: 'Зареєструватися',
    authGoRegister: 'Ще немає акаунту?',
    authGoLogin: 'Вже є акаунт?',
    authLinkRegister: 'Реєстрація',
    authLinkLogin: 'Увійти',
    authLoginError: 'Помилка входу',
    authRegisterError: 'Помилка реєстрації',
    // Cards
    cardsTitle: 'Картки для P2P',
    cardAdd: 'Додати картку',
    cardName: 'Назва',
    cardBank: 'Банк',
    cardLimit: 'Місячний ліміт (₴)',
    cardSave: 'Зберегти',
    cardCancel: 'Скасувати',
    cardNoCards: 'Немає карток. Додайте першу.',
    cardUsed: 'Використано',
    cardRemaining: 'Залишок',
    cardEdit: 'Ред.',
    cardDeactivate: 'Деактивувати',
    // Upload
    uploadTitle: 'Завантажити CSV',
    uploadDesc: 'Скинь скріни OKX в чат Claude — він розпарсить і поверне готовий CSV. Потім завантаж його тут.',
    uploadDrop: 'Натисни або перетягни CSV файл',
    uploadBtn: 'Завантажити',
    uploadLoading: '⏳ Завантажую...',
    uploadSuccess: '✅ Готово!',
    uploadSaved: 'Збережено нових записів',
    uploadSkipped: '⚠️ Пропущені рядки',
    uploadError: '❌ Помилка',
    uploadHowTitle: 'Як підготувати CSV',
    uploadFormatTitle: 'Формат CSV',
    uploadTemplate: '⬇️ Скачати шаблон CSV',
  },

  en: {
    appTitle: 'OKX P2P Tracker',
    loading: 'Loading...',
    error: 'Loading error',
    logout: 'Logout',
    tabDashboard: 'Dashboard',
    tabCards: 'Cards',
    tabUpload: 'Upload',
    period: 'Period',
    dateFrom: 'From',
    dateTo: 'To',
    applyFilter: 'Apply',
    resetFilter: 'Reset',
    filterThisMonth: 'This month',
    filterPrevMonth: 'Last month',
    filterThisYear: 'This year',
    statSold: 'Sold USDT → UAH',
    statBought: 'Spent UAH on buying',
    statProfit: 'P2P Profit',
    statProfitSub: 'sales − purchases',
    statDeposit: 'USDT Deposits',
    recentTx: 'Recent Transactions',
    noData: 'No data. Upload a CSV.',
    colType: 'Type',
    colDate: 'Date',
    colUsdt: 'USDT',
    colUah: 'UAH',
    colPrice: 'Price',
    colCounterparty: 'Counterparty',
    prevPage: '← Back',
    nextPage: 'Next →',
    pageOf: (p, t) => `Page ${p} of ${t}`,
    buy_usdt: '🟢 Buy USDT',
    sell_usdt: '🔴 Sell USDT',
    deposit: '💰 Deposit',
    withdrawal: '📤 Withdrawal',
    cancel_order: '↩️ Cancelled',
    internal: '🔄 Internal',
    other: '❓ Other',
    authLogin: 'Sign in',
    authRegister: 'Create account',
    authEmail: 'Email',
    authPassword: 'Password',
    authSubmitLogin: 'Sign in',
    authSubmitRegister: 'Register',
    authGoRegister: "Don't have an account?",
    authGoLogin: 'Already have an account?',
    authLinkRegister: 'Register',
    authLinkLogin: 'Sign in',
    authLoginError: 'Login error',
    authRegisterError: 'Registration error',
    cardsTitle: 'P2P Cards',
    cardAdd: 'Add card',
    cardName: 'Name',
    cardBank: 'Bank',
    cardLimit: 'Monthly limit (₴)',
    cardSave: 'Save',
    cardCancel: 'Cancel',
    cardNoCards: 'No cards. Add your first one.',
    cardUsed: 'Used',
    cardRemaining: 'Remaining',
    cardEdit: 'Edit',
    cardDeactivate: 'Deactivate',
    uploadTitle: 'Upload CSV',
    uploadDesc: 'Send OKX screenshots to Claude — it will parse and return a ready CSV. Then upload it here.',
    uploadDrop: 'Click or drag a CSV file',
    uploadBtn: 'Upload',
    uploadLoading: '⏳ Uploading...',
    uploadSuccess: '✅ Done!',
    uploadSaved: 'New records saved',
    uploadSkipped: '⚠️ Skipped rows',
    uploadError: '❌ Error',
    uploadHowTitle: 'How to prepare a CSV',
    uploadFormatTitle: 'CSV Format',
    uploadTemplate: '⬇️ Download template',
  },

  ru: {
    appTitle: 'OKX P2P Tracker',
    loading: 'Загрузка...',
    error: 'Ошибка загрузки',
    logout: 'Выйти',
    tabDashboard: 'Дашборд',
    tabCards: 'Карты',
    tabUpload: 'Загрузить скрин',
    period: 'Период',
    dateFrom: 'От',
    dateTo: 'До',
    applyFilter: 'Применить',
    resetFilter: 'Сбросить',
    filterThisMonth: 'Этот месяц',
    filterPrevMonth: 'Прошлый месяц',
    filterThisYear: 'Этот год',
    statSold: 'Продано USDT → UAH',
    statBought: 'Потрачено UAH на покупку',
    statProfit: 'Прибыль P2P',
    statProfitSub: 'продажи − покупки',
    statDeposit: 'Пополнения USDT',
    recentTx: 'Последние транзакции',
    noData: 'Нет данных. Загрузите CSV.',
    colType: 'Тип',
    colDate: 'Дата',
    colUsdt: 'USDT',
    colUah: 'UAH',
    colPrice: 'Цена',
    colCounterparty: 'Контрагент',
    prevPage: '← Назад',
    nextPage: 'Далее →',
    pageOf: (p, t) => `Стр. ${p} из ${t}`,
    buy_usdt: '🟢 Покупка USDT',
    sell_usdt: '🔴 Продажа USDT',
    deposit: '💰 Пополнение',
    withdrawal: '📤 Вывод',
    cancel_order: '↩️ Отмена',
    internal: '🔄 Внутренний',
    other: '❓ Прочее',
    authLogin: 'Вход в аккаунт',
    authRegister: 'Регистрация нового аккаунта',
    authEmail: 'Email',
    authPassword: 'Пароль',
    authSubmitLogin: 'Войти',
    authSubmitRegister: 'Зарегистрироваться',
    authGoRegister: 'Ещё нет аккаунта?',
    authGoLogin: 'Уже есть аккаунт?',
    authLinkRegister: 'Регистрация',
    authLinkLogin: 'Войти',
    authLoginError: 'Ошибка входа',
    authRegisterError: 'Ошибка регистрации',
    cardsTitle: 'Карты для P2P',
    cardAdd: 'Добавить карту',
    cardName: 'Название',
    cardBank: 'Банк',
    cardLimit: 'Месячный лимит (₴)',
    cardSave: 'Сохранить',
    cardCancel: 'Отмена',
    cardNoCards: 'Нет карт. Добавьте первую.',
    cardUsed: 'Использовано',
    cardRemaining: 'Остаток',
    cardEdit: 'Ред.',
    cardDeactivate: 'Деактивировать',
    uploadTitle: 'Загрузить CSV',
    uploadDesc: 'Скинь скрины OKX в чат Claude — он распарсит и вернёт готовый CSV. Потом загрузи его здесь.',
    uploadDrop: 'Нажми или перетащи CSV файл',
    uploadBtn: 'Загрузить',
    uploadLoading: '⏳ Загружаю...',
    uploadSuccess: '✅ Готово!',
    uploadSaved: 'Сохранено новых записей',
    uploadSkipped: '⚠️ Пропущенные строки',
    uploadError: '❌ Ошибка',
    uploadHowTitle: 'Как подготовить CSV',
    uploadFormatTitle: 'Формат CSV',
    uploadTemplate: '⬇️ Скачать шаблон CSV',
  },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('okx_lang') || 'uk')

  const setLanguage = (l) => {
    localStorage.setItem('okx_lang', l)
    setLang(l)
  }

  return (
    <LangContext.Provider value={{ lang, setLanguage, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
