import React, { createContext, useContext, useState } from 'react'

const LangContext = createContext(null)

export const LANGS = ['uk', 'en', 'ru']
export const LANG_LABELS = { uk: 'Укр', en: 'Eng', ru: 'Рус' }

const shared = {
  appTitle: 'OKX P2P Tracker',
  buy_usdt: '🟢 Купівля USDT',
  sell_usdt: '🔴 Продаж USDT',
  deposit: '💰 Поповнення',
  withdrawal: '📤 Виведення',
  cancel_order: '↩️ Скасування',
  internal: '🔄 Внутрішній',
  other: '❓ Інше',
}

export const T = {
  uk: {
    ...shared,
    buy_usdt: '🟢 Купівля USDT',
    sell_usdt: '🔴 Продаж USDT',
    deposit: '💰 Поповнення',
    withdrawal: '📤 Виведення',
    cancel_order: '↩️ Скасування',
    internal: '🔄 Внутрішній',
    other: '❓ Інше',
    loading: 'Завантаження...',
    error: 'Помилка завантаження',
    logout: 'Вийти',
    tabDashboard: 'Дашборд',
    tabCards: 'Карти',
    tabUpload: 'Завантажити скрін',
    // Filter
    period: 'Період',
    dateFrom: 'Від',
    dateTo: 'До',
    applyFilter: 'Застосувати',
    resetFilter: 'Скинути',
    filterThisMonth: 'Цей місяць',
    filterPrevMonth: 'Минулий місяць',
    filterThisYear: 'Цей рік',
    // Stats cards
    statSold: 'Продано USDT → UAH',
    statBought: 'Витрачено UAH на покупку',
    statProfit: 'Прибуток P2P',
    statProfitSub: 'по глоб. сер. курсу',
    statDeposit: 'Поповнення USDT',
    statAvgBuy: 'Сер. курс купівлі',
    statAvgSell: 'Сер. курс продажу',
    statSpread: 'Спред',
    statSpreadHint: '≥ 0.90 ₴ = 🟢 вигідно',
    statBuyCount: 'Угод BUY',
    statSellCount: 'Угод SELL',
    statWithdrawal: 'Виведено USDT',
    statProfitPct: 'Прибуток %',
    globalAvgNote: 'Прибуток по глобальному сер. курсу купівлі',
    // Transactions table
    recentTx: 'Останні транзакції',
    noData: 'Немає даних. Завантажте CSV.',
    colType: 'Тип',
    colDate: 'Дата',
    colUsdt: 'USDT',
    colUah: 'UAH',
    colPrice: 'Ціна',
    colCounterparty: 'Контрагент',
    prevPage: '←',
    nextPage: '→',
    pageOf: (p, t) => `Стор. ${p} з ${t}`,
    // Monthly analytics
    analyticsTitle: 'Аналітика по місяцях',
    colMonth: 'Місяць',
    colBuyUsdt: 'Куплено USDT',
    colBuyUah: 'Витрачено UAH',
    colSalary: 'Зарплата USDT',
    colTotalIn: 'Всього USDT',
    colAvgBuy: 'Сер. купівля',
    colSellUsdt: 'Продано USDT',
    colSellUah: 'Виручка UAH',
    colAvgSell: 'Сер. продаж',
    colProfit: 'Прибуток UAH',
    colProfitPct: '%',
    colWithdrawal: 'Виведено',
    colSpread: 'Спред',
    colBuySellCount: 'B/S',
    totalRow: 'ЗАГАЛОМ',
    salaryEditTitle: 'Зарплата USDT',
    salarySave: 'Зберегти',
    // Auth
    authLogin: 'Вхід в акаунт',
    authRegister: 'Реєстрація нового акаунту',
    authEmail: 'Email',
    authPassword: 'Пароль',
    authSubmitLogin: 'Увійти',
    authSubmitRegister: 'Зареєструватися',
    authGoRegister: 'Ще немає акаунту?',
    authGoLogin: 'Вже є акаунт?',
    authLinkRegister: 'Реєстрація',
    authLinkLogin: 'Увійти',
    // Cards
    cardsTitle: 'Картки для P2P',
    cardAdd: 'Додати картку',
    cardName: 'Назва',
    cardBank: 'Банк',
    cardLimit: 'Місячний ліміт (₴)',
    cardSave: 'Зберегти',
    cardCancel: 'Скасувати',
    cardNoCards: 'Немає карток. Додайте першу.',
    cardUsed: 'Використано',
    cardRemaining: 'Залишок',
    cardEdit: 'Ред.',
    cardDeactivate: 'Деактивувати',
    // Upload
    uploadTitle: 'Завантажити CSV',
    uploadDesc: 'Скинь скріни OKX в чат Claude — він розпарсить і поверне готовий CSV. Потім завантаж його тут.',
    uploadDrop: 'Натисни або перетягни CSV файл',
    uploadBtn: 'Завантажити',
    uploadLoading: '⏳ Завантажую...',
    uploadSuccess: '✅ Готово!',
    uploadSaved: 'Збережено нових записів',
    uploadSkipped: '⚠️ Пропущені рядки',
    uploadError: '❌ Помилка',
    uploadHowTitle: 'Як підготувати CSV',
    uploadFormatTitle: 'Формат CSV',
    uploadTemplate: '⬇️ Скачати шаблон CSV',
  },

  en: {
    ...shared,
    buy_usdt: '🟢 Buy USDT',
    sell_usdt: '🔴 Sell USDT',
    deposit: '💰 Deposit',
    withdrawal: '📤 Withdrawal',
    cancel_order: '↩️ Cancelled',
    internal: '🔄 Internal',
    other: '❓ Other',
    loading: 'Loading...',
    error: 'Loading error',
    logout: 'Logout',
    tabDashboard: 'Dashboard',
    tabCards: 'Cards',
    tabUpload: 'Upload',
    period: 'Period',
    dateFrom: 'From',
    dateTo: 'To',
    applyFilter: 'Apply',
    resetFilter: 'Reset',
    filterThisMonth: 'This month',
    filterPrevMonth: 'Last month',
    filterThisYear: 'This year',
    statSold: 'Sold USDT → UAH',
    statBought: 'Spent UAH on buying',
    statProfit: 'P2P Profit',
    statProfitSub: 'by global avg buy rate',
    statDeposit: 'USDT Deposits',
    statAvgBuy: 'Avg Buy Rate',
    statAvgSell: 'Avg Sell Rate',
    statSpread: 'Spread',
    statSpreadHint: '≥ 0.90 ₴ = 🟢 profitable',
    statBuyCount: 'BUY Trades',
    statSellCount: 'SELL Trades',
    statWithdrawal: 'Withdrawn USDT',
    statProfitPct: 'Profit %',
    globalAvgNote: 'Profit uses global avg buy rate',
    recentTx: 'Recent Transactions',
    noData: 'No data. Upload a CSV.',
    colType: 'Type',
    colDate: 'Date',
    colUsdt: 'USDT',
    colUah: 'UAH',
    colPrice: 'Price',
    colCounterparty: 'Counterparty',
    prevPage: '←',
    nextPage: '→',
    pageOf: (p, t) => `Page ${p} of ${t}`,
    analyticsTitle: 'Monthly Analytics',
    colMonth: 'Month',
    colBuyUsdt: 'Bought USDT',
    colBuyUah: 'Spent UAH',
    colSalary: 'Salary USDT',
    colTotalIn: 'Total USDT in',
    colAvgBuy: 'Avg Buy',
    colSellUsdt: 'Sold USDT',
    colSellUah: 'Revenue UAH',
    colAvgSell: 'Avg Sell',
    colProfit: 'Profit UAH',
    colProfitPct: '%',
    colWithdrawal: 'Withdrawn',
    colSpread: 'Spread',
    colBuySellCount: 'B/S',
    totalRow: 'TOTAL',
    salaryEditTitle: 'Salary USDT',
    salarySave: 'Save',
    authLogin: 'Sign in',
    authRegister: 'Create account',
    authEmail: 'Email',
    authPassword: 'Password',
    authSubmitLogin: 'Sign in',
    authSubmitRegister: 'Register',
    authGoRegister: "Don't have an account?",
    authGoLogin: 'Already have an account?',
    authLinkRegister: 'Register',
    authLinkLogin: 'Sign in',
    cardsTitle: 'P2P Cards',
    cardAdd: 'Add card',
    cardName: 'Name',
    cardBank: 'Bank',
    cardLimit: 'Monthly limit (₴)',
    cardSave: 'Save',
    cardCancel: 'Cancel',
    cardNoCards: 'No cards. Add your first one.',
    cardUsed: 'Used',
    cardRemaining: 'Remaining',
    cardEdit: 'Edit',
    cardDeactivate: 'Deactivate',
    uploadTitle: 'Upload CSV',
    uploadDesc: 'Send OKX screenshots to Claude — it will parse and return a ready CSV. Then upload it here.',
    uploadDrop: 'Click or drag a CSV file',
    uploadBtn: 'Upload',
    uploadLoading: '⏳ Uploading...',
    uploadSuccess: '✅ Done!',
    uploadSaved: 'New records saved',
    uploadSkipped: '⚠️ Skipped rows',
    uploadError: '❌ Error',
    uploadHowTitle: 'How to prepare a CSV',
    uploadFormatTitle: 'CSV Format',
    uploadTemplate: '⬇️ Download template',
  },

  ru: {
    ...shared,
    buy_usdt: '🟢 Покупка USDT',
    sell_usdt: '🔴 Продажа USDT',
    deposit: '💰 Пополнение',
    withdrawal: '📤 Вывод',
    cancel_order: '↩️ Отмена',
    internal: '🔄 Внутренний',
    other: '❓ Прочее',
    loading: 'Загрузка...',
    error: 'Ошибка загрузки',
    logout: 'Выйти',
    tabDashboard: 'Дашборд',
    tabCards: 'Карты',
    tabUpload: 'Загрузить скрин',
    period: 'Период',
    dateFrom: 'От',
    dateTo: 'До',
    applyFilter: 'Применить',
    resetFilter: 'Сбросить',
    filterThisMonth: 'Этот месяц',
    filterPrevMonth: 'Прошлый месяц',
    filterThisYear: 'Этот год',
    statSold: 'Продано USDT → UAH',
    statBought: 'Потрачено UAH на покупку',
    statProfit: 'Прибыль P2P',
    statProfitSub: 'по глоб. ср. курсу',
    statDeposit: 'Пополнения USDT',
    statAvgBuy: 'Ср. курс покупки',
    statAvgSell: 'Ср. курс продажи',
    statSpread: 'Спред',
    statSpreadHint: '≥ 0.90 ₴ = 🟢 выгодно',
    statBuyCount: 'Сделок BUY',
    statSellCount: 'Сделок SELL',
    statWithdrawal: 'Выведено USDT',
    statProfitPct: 'Прибыль %',
    globalAvgNote: 'Прибыль по глобальному ср. курсу покупки',
    recentTx: 'Последние транзакции',
    noData: 'Нет данных. Загрузите CSV.',
    colType: 'Тип',
    colDate: 'Дата',
    colUsdt: 'USDT',
    colUah: 'UAH',
    colPrice: 'Цена',
    colCounterparty: 'Контрагент',
    prevPage: '←',
    nextPage: '→',
    pageOf: (p, t) => `Стр. ${p} из ${t}`,
    analyticsTitle: 'Аналитика по месяцам',
    colMonth: 'Месяц',
    colBuyUsdt: 'Куплено USDT',
    colBuyUah: 'Потрачено UAH',
    colSalary: 'Зарплата USDT',
    colTotalIn: 'Всего USDT',
    colAvgBuy: 'Ср. покупка',
    colSellUsdt: 'Продано USDT',
    colSellUah: 'Выручка UAH',
    colAvgSell: 'Ср. продажа',
    colProfit: 'Прибыль UAH',
    colProfitPct: '%',
    colWithdrawal: 'Выведено',
    colSpread: 'Спред',
    colBuySellCount: 'B/S',
    totalRow: 'ИТОГО',
    salaryEditTitle: 'Зарплата USDT',
    salarySave: 'Сохранить',
    authLogin: 'Вход в аккаунт',
    authRegister: 'Регистрация нового аккаунта',
    authEmail: 'Email',
    authPassword: 'Пароль',
    authSubmitLogin: 'Войти',
    authSubmitRegister: 'Зарегистрироваться',
    authGoRegister: 'Ещё нет аккаунта?',
    authGoLogin: 'Уже есть аккаунт?',
    authLinkRegister: 'Регистрация',
    authLinkLogin: 'Войти',
    cardsTitle: 'Карты для P2P',
    cardAdd: 'Добавить карту',
    cardName: 'Название',
    cardBank: 'Банк',
    cardLimit: 'Месячный лимит (₴)',
    cardSave: 'Сохранить',
    cardCancel: 'Отмена',
    cardNoCards: 'Нет карт. Добавьте первую.',
    cardUsed: 'Использовано',
    cardRemaining: 'Остаток',
    cardEdit: 'Ред.',
    cardDeactivate: 'Деактивировать',
    uploadTitle: 'Загрузить CSV',
    uploadDesc: 'Скинь скрины OKX в чат Claude — он распарсит и вернёт готовый CSV. Потом загрузи его здесь.',
    uploadDrop: 'Нажми или перетащи CSV файл',
    uploadBtn: 'Загрузить',
    uploadLoading: '⏳ Загружаю...',
    uploadSuccess: '✅ Готово!',
    uploadSaved: 'Сохранено новых записей',
    uploadSkipped: '⚠️ Пропущенные строки',
    uploadError: '❌ Ошибка',
    uploadHowTitle: 'Как подготовить CSV',
    uploadFormatTitle: 'Формат CSV',
    uploadTemplate: '⬇️ Скачать шаблон CSV',
  },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('okx_lang') || 'uk')
  const setLanguage = (l) => { localStorage.setItem('okx_lang', l); setLang(l) }
  return (
    <LangContext.Provider value={{ lang, setLanguage, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
